name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: corona_tracker
    permissions: 
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Show Files in Workspace
        run: ls -la && ls -R src

      - name: Run SonarScanner with Debug
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=corona_tracker \
            -Dsonar.sources=. \
            -Dsonar.inclusions=**/*.js,**/*.ts \
            -Dsonar.projectVersion=1.0.${{ github.run_number }} \
            -Dsonar.host.url=http://192.168.0.104:9000 \
            -Dsonar.login=$SONAR_TOKEN \
            -X
