name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: corona_tracker
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Required for SonarQube's full analysis context

      - uses: SonarSource/sonarqube-scan-action@v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
